version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - pip install -U pip setuptools wheel twine
      - pip install -r requirements.txt
  pre_build:
    commands:
      - PYTEST_DEBUG=1 pytest --collect-only

